import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/AccountSettings.module.css";
import NavBar from "@/Components/Navbar";
import { Montserrat } from "next/font/google"
import Image1 from "@/public/img/nature-4964153_1920.jpg"
import ArrowLeft from "@/Components/Shapes/Arrows/ArrowLeft";
import Pencil from "@/public/img/icons8-pencil-50.png"

const montserrat = Montserrat({
  subsets: ['latin'],
});
export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mobileContainer}>
      <main className={`${styles.main} ${montserrat.main}`}>
        <div className={styles.container}>
          <div className={styles.imageContainer}>
            <Image
              src={Image1}
              width={150}
              height={150}
            />
          </div>
          <h2 className={styles.name}>Drake Williams</h2>
          <h3 className={styles.email}>drakewilliamsmusic@hotmail.net</h3>
          <h4 className={styles.number}>604-069-7201</h4>

          <div className={styles.editOptions}>
            <div className={styles.optionContainer}>
              <Image
              src={Pencil}
              width={25}
              height={25}
              className={styles.pencil}
              />
              <h4>Account Name: </h4>
              <p>certifiedDrake92</p>
            </div>
            <div className={styles.optionContainer}>
              <Image
              src={Pencil}
              width={25}
              height={25}
              className={styles.pencil}
              />
              <h4>Display Name: </h4>
              <p>Drake Williams</p>
            </div>
            <div className={styles.optionContainer}>
              <Image
              src={Pencil}
              width={25}
              height={25}
              className={styles.pencil}
              />
              <h4>Pronouns: </h4>
              <p>He / Him</p>
            </div>
            <div className={styles.optionContainer}>
              <Image
              src={Pencil}
              width={25}
              height={25}
              className={styles.pencil}
              />
              <h4>Bio:</h4>
              <p>“Keke do you love me....."</p>
            </div>
            <div className={styles.optionContainer}>
              <Image
              src={Pencil}
              width={25}
              height={25}
              className={styles.pencil}
              />
              <h4>E-Mail: </h4>
              <p>drakewilliamsmusic@hotmail.net</p>
            </div>
            <div className={styles.optionContainer}>
              <Image
              src={Pencil}
              width={25}
              height={25}
              className={styles.pencil}
              />
              <h4>Phone Number: </h4>
              <p>604-069-7201</p>
            </div>
          </div>
        </div>
      </main>
      <NavBar />    
      </div>

    </>
  );
}
