import Head from "next/head";
import styles from "@/styles/Components.module.css"
import Image from "next/image";
import NavBar from "@/Components/Navbar";
import Header from "@/Components/Header"
import Button1 from "@/Components/Buttons/Oscar"
import Button2 from "@/Components/Buttons/Button2"
import Button3 from "@/Components/Buttons/Button3";
import Carousel from "@/Components/Carousel";
<<<<<<< Updated upstream
=======
import Button4 from "@/Components/Buttons/Button4";
import Link from 'next/link'
>>>>>>> Stashed changes

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={`${styles.main}`}>
        <div className={styles.buttonContainer}>
          <Button1/>
          <Button2/>
          <Button3/>
        </div>
        <div className={styles.carousel}>
          <Carousel/>
        </div>
      <NavBar/>
      </main>
    </>
  );
}
