import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Courses.module.css";
import { Montserrat } from "next/font/google";
import Oscar from "@/Components/Oscar"
import CourseQuestions from "@/Components/CourseQuestions"
import Header from "@/Components/Header";
import NavBar from "@/Components/Navbar";
import Circles from "@/Components/Shapes/Circles";
import QuestionMark from "@/Components/Shapes/Tooltips/QuestionMark";

const montserrat = Montserrat({ subsets: ['latin'] })
export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mobileContainer}>
      <Circles
        title="Ask"
        />
      <main className={`${styles.main} ${montserrat.className}`}>
      <div className={styles.questionContainer}>
        <QuestionMark
        tip={"Click the level that best describes you skill level in this subject"}
        />
        </div>
      <div className={styles.oscarContainer}>
      <Oscar/>
      </div>
      <CourseQuestions/>
      <NavBar/>
      </main> 
      </div>

    </>
  );
}
