"use client";

import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Settings.module.css";
import NavBar from "@/Components/Navbar";
import { Montserrat } from "next/font/google"
import {useEffect, useState} from "react"

const montserrat = Montserrat({ 
  subsets: ['latin'],
});
export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${montserrat.main}`}>
        <p>Hello!</p>
        <div className={styles.container}>
          <button
          onClick={async () => {
            const response = await fetch("/api/chat-gpt", {
              method: "POST" ,
              headers: {
                "Content-Type": "application/json", 
              },
              body: JSON.stringify({
                someData: true,
              }),
            });
            console.log("RESPONSE", response)
          }}
          >
            Hit API
          </button>
        </div>
      </main>
      <NavBar/>
    </>
  );
}
