import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Courses.module.css";
import { Montserrat } from "next/font/google";
import Oscar from "@/Components/Oscar"
import Goals from "@/Components/Goals"
import Images from "@/Components/images";
import Header from "@/Components/Header";
import NavBar from "@/Components/Navbar";

const montserrat = Montserrat({ subsets: ['latin'] })
export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mobileContainer}>
      <main className={`${styles.main} ${montserrat.className}`}>
      <Header name="Ask"/>
      <Oscar/>
      <Goals/>
      <NavBar/>
      </main> 
      </div>

    </>
  );
}
