import Head from "next/head";
import NavBar from "@/Components/Navbar";
import Image from "next/image";
import styles from "@/styles/NewSubject.module.css";
import { Montserrat } from "next/font/google";
import CategoryButton from "@/Components/Buttons/CategoriesButton";

const montserrat = Montserrat({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.mobileContainer}>
        <div className={`${styles.background__circle}`}></div>
        <div className={`${styles.background__circle2}`}></div>
        <main className={`${styles.main} ${montserrat.className}`}>
            <div className={styles.heading__section}>
                <div className={styles.heading__container}>
                    <h1 className={styles.heading}>
                        Learn Something New
                    </h1>
                </div>
            </div>
            <div className={styles.subheading__section}>
                <div className={styles.subheading__container}>
                    <h2 className={styles.subhead}>
                        Categories
                    </h2>
                </div>
            </div>
            <div className={styles.category__button__container}>
                <CategoryButton title="Arts / Creative" backgroundImage="/img/arts.jpg"/>
                <CategoryButton title="Technical" backgroundImage="/img/technicalz.jpg"/>
                <CategoryButton title="Fitness / Lifestyle" backgroundImage="/img/gym.jpg"/>
            </div>
        <NavBar/>
      </main>  
      </div>

    </>
  );
}